### ISSUE TITLE
Mesh geometries do not update on playback

### ISSUE THREAD

**Issue by virokannas** [ospray/hdospray#1]
When playing back the timeline (in usdview), geometries do not get updated to reflect changes - e.g. animated characters stay in their initial positions.

If I change to GL and back to OSPRay, it updates to reflect the current frame.

Sidenote:
Great job with the release, this is much easier to compile into USD now! Looking forward to how this develops.

**Comment by BruceCherniak** [comment]
I'll take a look.  Do you have a simple animated scene file that I can work with?

**Comment by carsonbrownlee** [comment]
Thanks for the feedback!  Yeah, since we aren't a studio the only usd content we test with are the publicly available ones; none of which are animated.

**Comment by virokannas** [comment]
Never realized all available samples are static - someone should definitely fix that!

Here's a deforming torus of dough - it uses time samples for the vertex data in a 90-frame looping animation. You'll see the deformation with GL in usdview, and the odd triangular patterns that form if attempting playback with OSDPray.

I believe this reflects the most common way to export baked animation for skinned characters or other objects into USD.

[torus_dough.usda.zip](https://github.com/ospray/hdospray/files/2974065/torus_dough.usda.zip)

**Comment by carsonbrownlee** [comment]
sorry for belated response, just got back from a conference.  I managed to get the "dancing donut" working with OSPRay.  I'll update this thread when the changes are pushed to github, likely first to dev and then the next patch release.

**Comment by virokannas** [comment]
That's great news! Thank you so much, i'll try out the dev once it's out.

**Comment by carsonbrownlee** [comment]
I have found a second animated source here:  https://groups.google.com/forum/#!topic/usd-interest/dj9tUT8NcpI  this is a good stress test as it's taking longer to update per frame than it should for the amount of geometry present.

**Comment by carsonbrownlee** [comment]
update: this will be included in the 0.2.2 release coming soon along with a number of bug fixes.  We have not yet decided to expose devel branch to github, perhaps in the future.

**Comment by virokannas** [comment]
That's great! And I'm sure people appreciate access to bleeding edge as well, even if just to see what's coming. It seems that so far hdOSPRay is the only open-source project providing an actual render output (other than just occlusion)... and it's not a bad one either.

**Comment by carsonbrownlee** [comment]
It took us longer than expected, but 0.2.2 is out which has been tested with two different animation sources.  Let is know if you run into any issues!  We are going to look into exposing other branches- you should not have to wait a month just to get access to a wip fix/feature.

**Comment by BruceCherniak** [comment]
Hi Simo (@simpassi), did this resolve the animation problem for you?  If so, can we close this issue?

**Comment by virokannas** [comment]
Hi, I tried with building with the latest commits (both hdospray and ospray) and it seems like the problem still exists. I will try next doing a completely clean (non-incremental) build of both OSPRay and hdospray...

**Comment by virokannas** [comment]
Here's an example of how it looks like when playing back the sequence:
<img width="576" alt="Screen Shot 2019-05-14 at 4 45 23 PM" src="https://user-images.githubusercontent.com/38055305/57731046-cc21ff80-7667-11e9-9d5e-d202925508ee.png">

**Comment by carsonbrownlee** [comment]
Just double checked from a clean build of github master with this dataset and it's working on my mac.  One thing to try - the pxr cmake scripts copy the headers into your build directory, make sure those are cleared out and then rebuild and make install.  Also clear out "usdinstall dir"/plugin/hdOSPRay* and re-install just to make sure.

**Comment by virokannas** [comment]
That was it - I cleaned up and reinstalled and it works now. Thank you very much!
