### ISSUE TITLE
Ptex module is not accesible

### ISSUE THREAD

**Issue by iqch** [ospray/hdospray#10]
I see, you've published link to ptex ospray module, but it points to nowhere. Is that project abandoned? I remember a year ago I've played with it, but cannot find sources downloaded now.

**Comment by carsonbrownlee** [comment]
it appears it may have been taken down from github, though I only use an internal repo.  @BruceCherniak what happened to the public facing ptex module on github?

**Comment by BruceCherniak** [comment]
module_ptex is hosted on gitlab (https://gitlab.com/ospray/module_ptex) rather than github.  This gitlab repo is publicly available.

**Comment by iqch** [comment]
[image: 2021-09-23_21-06-07.png]

чт, 23 сент. 2021 г. в 00:25, Bruce Cherniak ***@***.***>:

**Comment by iqch** [comment]
![2021-09-23_21-06-07](https://user-images.githubusercontent.com/2112777/134560956-190cebc7-c4a6-40e0-96fe-ef74f722c997.png)
does anyone check links published?

**Comment by BruceCherniak** [comment]
Indeed, we do.  Mistakes do happen.  We'll get it updated.  @carsonbrownlee can you create an issue to update the hdospray README link?

**Comment by iqch** [comment]
I see no repo at link published.
Ok. let it be closed.

**Comment by BruceCherniak** [comment]
apologies, open is fine, I figured that was the only issue.  This link https://gitlab.com/ospray/module_ptex does not work?  This is where the module_ptex has been hosted for as long as I can remember and our gitlab repo to this _should be_ publicly visible.

**Comment by iqch** [comment]
No, it doesn't.

чт, 23 сент. 2021 г. в 21:24, Bruce Cherniak ***@***.***>:

**Comment by iqch** [comment]
which problems are with github hosting?

чт, 23 сент. 2021 г. в 21:38, Bruce Cherniak ***@***.***>:

**Comment by BruceCherniak** [comment]
Again, apologies.  I appear to be less informed than anyone else here.

> it appears it may have been taken down from github, though I only use an internal repo. @BruceCherniak what happened to the public facing ptex module on github?

@carsonbrownlee, I am not sure what happened with the github repo.

**Comment by carsonbrownlee** [comment]
yeah I think there was a github repo that mysteriously disappeared... hopefully not with my changes:)  @BruceCherniak do you mind if I create a new github repo for this off our official github project?

**Comment by carsonbrownlee** [comment]
update: the github repo was taken offline unexpectedly.  We'll have to wait until this can be reviewed and approved unfortunately and I'll update the docs.  And for the record, I did test the link before publishing time, so this was pretty recent:)

**Comment by iqch** [comment]
Ok. Anyway, it is not a biggest issue.

пт, 24 сент. 2021 г. в 21:45, carsonbrownlee ***@***.***>:

**Comment by carsonbrownlee** [comment]
update as of oct 2023 - ptex module is still internal/collaborator testing only due to the overhead of releasing new official github projects and the only real use case we currently have being the Moana scene.  For anyone looking for the ptex module, please contact us.
