### ISSUE TITLE
TBB version harmonization

### ISSUE THREAD

**Issue by nyue** [ospray/hdospray#15]
USD requires an older version of TBB which provides `include/tbb/tbb_stddef.h`

Whereas OSPray requires a more recent version of TBB

Does any know if there is one version of TBB that is usable by both USD and OSPray ?

I have difficulty building hdospray.

Cheers

**Comment by carsonbrownlee** [comment]
Hi nyue, have you tried the superbuild?  Also, we are readying a release of USD 21.08 / houdini 19 support.

**Comment by carsonbrownlee** [comment]
closing out issue due to lack of responses.  For anyone wondering, it is recommended to follow the tbb versioning in the superbuild.
