### ISSUE TITLE
Ensure Ospray actually renders with USD 23.xy 

### ISSUE THREAD

**Issue by pberto** [ospray/hdospray#18]
We gave it a quick spin here on both Linux and Windows and could not get a successful render. We tried older and newer USD versions.

Obviously there are some bugs in hdOspray that prevent the delegate to work correctly.

Could someone at Intel have a look at this?

- update linking with a modern USD version like `23.xy` (any recent version)
- load in `usdview`
- ensure it works by actually seeing it render something :)

**Comment by carsonbrownlee** [comment]
hi pberto,
sorry to hear you ran into issues and yes you are right the USD version is out of date.
* hdOSPRay's unreleased 1.0 is based on 23.02, which is currently waiting on OSPRay's upcoming official gpu release (3.0).  This version is also tested to work with windows/mac as well as linux.  If you want, I can  send you the unreleased source for testing.
* The current codebase on public github will likely only work with linux and tested with ubuntu 22.04 and USD 22.08.  Are you seeing an error or it just is not producing the correct image?  Please try ***usd source***/extras/usd/tutorials/traversingStage/HelloWorld.usda as a baseline.

**Comment by carsonbrownlee** [comment]
hdOSPRay 1.0 released with 23.x support, please let me know if you run into any issues.
