### ISSUE TITLE
Conflicting windows macros with local variable names

### ISSUE THREAD

**Issue by Slazzo** [ospray/hdospray#19]
When building with CMake and MSVC against Houdini on Windows this defines from Windows headers conflict with the hdospray code
`#define far     /* nothing */`
`#define near    /* nothing */ `

Particularly found in renderPass.cpp `line 343`,
`const float near = ((m1 - 1.f) * near) / (m1 + 1.f);`

Also notice using uninitialized variable `near`.

**Comment by carsonbrownlee** [comment]
hi Slazzo, windows/mac support are in the upcoming 1.0 release and fix these and many other issues.  That release is blocked on the public release of OSPRay 3.0, which I've been told is coming out any day now.  If you are building the current public code against windows, there are several issues you will run into, including runtime loading of the plugin in USD.  If you need this code immediately, contact me and I can likely get you access to the 1.0 RC for development.

**Comment by carsonbrownlee** [comment]
OSPRay 1.0 release out which fixes windows build.
