### ISSUE TITLE
BasisCurve support

### ISSUE THREAD

**Issue by virokannas** [ospray/hdospray#2]
This might already be on the roadmap, but USD BasisCurve render support would be great (enabling things such as hair systems).

I believe OSPRay already supports bspline and bezier curves?

**Comment by carsonbrownlee** [comment]
yes OSPRay supports curves.  I'm cleaning up a subd implementation now, we will likely take a look at curves next.  We don't have any data that uses it beyond the one in the tutorial though.

**Comment by virokannas** [comment]
I can try to create a lightweight test file and upload it here, if that helps.

**Comment by carsonbrownlee** [comment]
we'll start with the basic tutorial.  If your test file would test conditions beyond the tutorial then by all means we can make sure we support it.

**Comment by virokannas** [comment]
The basic tutorial sounds great, it covers all the different curve types - and the rest was already in #1, updating per frame since it's most likely going to be hair and other deforming curve sets anyway.

**Comment by carsonbrownlee** [comment]
Added in 0.7.
