### ISSUE TITLE
ISPCRT Error (1): Missing ISPCLaunch_cpu symbol?

### ISSUE THREAD

**Issue by gedalia** [ospray/hdospray#24]
Hello, I'm building hdospray on a ubuntu 22.04 system, and when I try and run the renderer I get :
ISPCRT Error (1): Missing ISPCLaunch_cpu symbol
I've tried 2 different computers (laptop/desktop) both fail the same way. usdview will work as long as I don't use the ospray rendering plugin, but crashes as soon as I switch to it. Any suggestions?

**Comment by rbinyahib** [comment]
Hi @gedalia 

Can you please try including this line `export LD_LIBRARY_PATH=${HDOSPRAY_ROOT}/lib64:${LD_LIBRARY_PATH}` in the `<install_dir>/setup_hdospray.sh` script and check if that fixes the problem.

**Comment by gedalia** [comment]
thanks, that was the issue. Hopefully the next person who hits it will stumble on this answer via google, (might be worth updating the script generation too)
