### ISSUE TITLE
usd 19.11?

### ISSUE THREAD

**Issue by maxnbk** [ospray/hdospray#4]
in usd 19.11, pxr/imaging/hdx/rendererPlugin.h is not a file anymore - probably many other changes, but I can't ID all of them presently - is there any branch or work to update hdospray for newer USD versions? (we're on 19.05 and 19.11 currently)

**Comment by carsonbrownlee** [comment]
While this reply is far too late to be useful, we update the USD version as needed to track against the versions used for maya/houdini so we may be a few versions back from the latest.  Each release of hdospray is pegged to a single USD version, which you can find in the tag of the release.  In general, it's probably not too much effort to port it a few versions up or down but we can't tell what issues you may run into.
