### ISSUE TITLE
Support for UDIM workflow

### ISSUE THREAD

**Issue by johguenther** [ospray/hdospray#5]
see https://github.com/ospray/ospray/issues/487

**Comment by DanEnglesson** [comment]
Thanks for moving this Johannes here to hdOspray.

Cheers,
Dan

**Comment by carsonbrownlee** [comment]
With the release of AL's test scene, it's apparent how glaring an omission this is.  We are actively looking into this now.

**Comment by DanEnglesson** [comment]
That is great news to hear that you are looking into it!

**Comment by carsonbrownlee** [comment]
update: we have prototyped udim support, but it won't make it until the next release cycle to give more time for testing.  0.8 will be landing very shortly.

**Comment by DanEnglesson** [comment]
Great! Looking forward to test it out!

**Comment by carsonbrownlee** [comment]
UDIM support was added in 0.8.
