### ISSUE TITLE
Versions mismatching

### ISSUE THREAD

**Issue by iqch** [ospray/hdospray#6]
What if we should use for USD building older tbb versions, than ospray using to build itself?
What about compatibility at all? I tried to build hydra delegate wit 21.05 version - it was failed, because - yes, pixar changes API very often. 21.08 (current) has same issues, I seem, just didn't check this while

**Comment by carsonbrownlee** [comment]
hello, internally we currently build against usd 20.08 (mostly for houdini).  Yes, the hydra interface changes pretty regularly so each release of hdOSPRay has to be tied to a specific USD release unfortunately, you can check this based on the release tag.  I'm currently using tbb 2019 u8 if that answers your question.  We also have an internal superbuild that should help with building all of the various dependencies, which I'm polishing before public release, but that will not help with USD and delegate version mismatches unfortunately.
