### ISSUE TITLE
Houdini + usdview and hdospray plugin

### ISSUE THREAD

**Issue by nyue** [ospray/hdospray#8]
I have build the render delegate

```
$ ls /home/nyue/projects/OSPray/hdospray/superbuild/install/plugin/usd/
hdOSPRay  hdOSPRay.so
```

I have not been able to use the plugin as the render delegate

What is the correct way to tell usdview about this new OSPRay render delegate ?

I tried the following but it does not register with usdview

```
env  PXR_PLUGINPATH_NAME=/home/nyue/projects/OSPray/hdospray/superbuild/install/plugin/usd usdview /home/nyue/Downloads/USD/Kitchen_set/Kitchen_set.usd
```

Cheers

**Comment by nyue** [comment]
Figured it out. The plugin path needs to point to the resources directory

```
env  PXR_PLUGINPATH_NAME=~/projects/OSPray/hdospray/superbuild/install/plugin/usd/hdOSPRay/resources
```

**Comment by carsonbrownlee** [comment]
thank you for this comment, sounds like we will need to issue a hot fix.

**Comment by carsonbrownlee** [comment]
@nyue just to make sure here, it seems you were not using the superbuild, is that correct?  From the cmakelists.txt file located here https://github.com/ospray/hdospray/blob/master/scripts/superbuild/CMakeLists.txt, it sets the PXR_PLUGINPATH_NAME to the correct folder already.  Perhaps I should put a guide in the build instructions for those that want to build houdini support without using the superbuild.

**Comment by carsonbrownlee** [comment]
@nyue just to make sure here, it seems you were not using the superbuild, is that correct?  From the cmakelists.txt file located here https://github.com/ospray/hdospray/blob/master/scripts/superbuild/CMakeLists.txt, it sets the PXR_PLUGINPATH_NAME to the correct folder already.  Perhaps I should put a guide in the build instructions for those that want to build houdini support without using the superbuild.

**Comment by nyue** [comment]
FYI am using superbuild.

Adding information about PXR_PLUGINPATH_NAME is useful information, I think it should be done independent of whether the user use superbuild or manual build.

**Comment by carsonbrownlee** [comment]
I see, can you post the generated setup_hdospray.sh script please?  I completely agree about build information outside of the superbuild, that was an oversight.

**Comment by nyue** [comment]
Didn't know about that file, I may have miss the information in the README.md

Yes, the setup looks correct, it has a path set to the resources directory.

```
nyue@head0:~/projects/OSPray/hdospray/superbuild$ cat install/setup_hdospray.sh 
export HDOSPRAY_ROOT=/home/nyue/projects/OSPray/hdospray/superbuild/install
export LD_LIBRARY_PATH=${HDOSPRAY_ROOT}/lib:${LD_LIBRARY_PATH}
cd /opt/sesi/hfs-py3-18.5.547/toolkit/toolkit/cmake/../../
source houdini_setup_bash
cd -
export PXR_PLUGINPATH_NAME=${HDOSPRAY_ROOT}/plugin/usd/hdOSPRay/resources:${PXR_PLUGINPATHNAME}
```

**Comment by carsonbrownlee** [comment]
thank you, we'll add a section on running with houdini outside of the setup script in the next release.
