### ISSUE TITLE
Building Win10+MSVS2019+H18.5Py37

### ISSUE THREAD

**Issue by iqch** [ospray/hdospray#9]
I've built this configuration. Everything works nice finally, but cmake files should be corrected a bit to pass all build automatically.
1. First - it lacks paths to tbb libraries for OSPRay superbuild components, which require it. To be honest - they should be built over Houdini tbb, but some components can find tbb somewhere else, some - lack it at all. I decide not invent too much  and compose API-folder from houdini's tbb headers/libs, placed it separately and add -DTBB_ROOT=<somewhere> clause to these components config-rule custom build step
2.  root superbuild solution which produces two nested solution for ospray itself and hydra delegate lacks correct paths to tbb too, I fixed it manually with same method. For OSPRay it was almost all it need to be build - except of some strange fnot-found binaries, which it tries to copy during install ospray itself - I just erase these lines. I suspect they were dedicated to tbb.
3. hdOspray have some issues with absence of usd, python, hboost and OIIO libraries pointed. After correction - everything builds silently.
4. There is some components like oidn and embree3 already built in houdini. Is it a good idea to use them prebuilt to save time?
I prepared some screenshots with more detailed description, if you need them.
Thank you, anyway, I spend just 3 hours to figure and build this nice and fast module. To figure with hdCycles I spend about a weeek :)

**Comment by carsonbrownlee** [comment]
Glad to hear it's running on Windows, which we don't test against currently. tbb should be built by default by the superbuild script using flag "DOWNLAD_TBB", are you not seeing a built tbb showing in your install directory?  It's a good point to use houdini's existing tbb to avoid conflicts when USE_HOUDINI is enabled.  The tbb location should be set to the superbuild install location by "-DTBB_PATH=${TBB_PATH}" set in scripts/superbuild/cmake/ep_ospray.cmake file.  Can you please copy and paste the errors you were seeing with #3?

**Comment by iqch** [comment]
I can leave some screenshots
### starting conditions
![starting conditions](https://user-images.githubusercontent.com/2112777/133299505-042e0b78-43f7-44c5-9f5a-2fe98f764730.png)
### cmake altering
![2021-09-12_04-30-38](https://user-images.githubusercontent.com/2112777/133301836-bf0ef074-bf4b-4f56-a377-edbf6e095f10.png)
### configure rules altering
![configure rules altering](https://user-images.githubusercontent.com/2112777/133299874-016a4372-ba10-45e8-bdfb-b68e69f4e2c0.png)
### why these field has such values?
![why these field has such values?](https://user-images.githubusercontent.com/2112777/133299996-8b3db19b-bbc8-47d2-b7d3-02a6a576fe86.png)
### that clause had no effect
![that clause had no effect](https://user-images.githubusercontent.com/2112777/133300188-59a481ef-2fec-473e-8d6e-a06168ecf27a.png)
### reason of failing ospray install
![reason of failing ospray install](https://user-images.githubusercontent.com/2112777/133300405-251b4376-3eba-40d2-9931-1dab663ce929.png)
### additional library path setup for hdospray itself
![additional library path setup for hdospray itself](https://user-images.githubusercontent.com/2112777/133300550-e90919f4-dc3f-4d80-bb57-dd054b71722b.png)
### required houdini libs for hdospray
![required houdini libs for hdospray](https://user-images.githubusercontent.com/2112777/133300669-e44d53dc-a30b-4aff-8f2f-bbebfc5f23e3.png)
### more houdini libs for hdospray
![more houdini libs for hdospray](https://user-images.githubusercontent.com/2112777/133300775-29033568-cf7d-45ff-998c-b2addb2fb6f7.png)
### possible to use these libs, instead of building them?
![possible to use these libs, instead of building them?](https://user-images.githubusercontent.com/2112777/133300898-2705416c-1d55-47e4-b6d5-3a414eb249a5.png)
### as they are existed in houdini
![as they are existed in houdini](https://user-images.githubusercontent.com/2112777/133301068-a2dca4a8-9616-4a4f-82fb-c4e35e65c84c.png)

**Comment by carsonbrownlee** [comment]
@iqch your detailed bug reports are much appreciated!

**Comment by carsonbrownlee** [comment]
for "cmake altering" image, why did you set superbuild_houdini_dir inside of the cmakelists file instead of through the cmake variable?  Were you having issues setting it through cmake?

**Comment by iqch** [comment]
No, just decide to no mess too much with cmdline args

**Comment by carsonbrownlee** [comment]
Windows now supported and tested with working with win10 and hdOSPRay 1.0.
